name: Unzip

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install unzip
        run: sudo apt-get install unzip

      - name: Unzip file
        run: unzip project_flask.zip -d .

      - name: Commit unzipped files
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Unzipped project"
          git push
